services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $namespace: '%overblog_graphql.class_namespace%'

    _instanceof:
        Overblog\GraphQLBundle\Generator\TypeBuilder\TypeBuilderInterface:
            tags: [overblog_graphql.type_builder]


    Overblog\GraphQLBundle\Generator\TypeBuilder\:
        resource: '../../Generator/TypeBuilder/*'


    Overblog\GraphQLBundle\Generator\Converter\ExpressionConverter:
        arguments:
            - '@Overblog\GraphQLBundle\ExpressionLanguage\ExpressionLanguage'
